
[[Smsdedbga]]

== Supervisor Domain External Trace and Debug Allow Controls

This chapter describes two extensions `Smsdedbga` and `Smsdetrca` that enable
the RDSM to enforce isolation of supervisor domains when external debug and
external trace mechanisms are being utilized.

`Smsdedbga` defines the `SEDA` bit in the `msdcfg` CSR that specifies if a
supervisor domain is allowed to be externally-debugged.

Similarly, `Smsdetrca` defines the `SETA` bit in the `msdcfg` CSR that specifies
if a supervisor domain is allowed to be externally-traced cite:[ExtDbg].

External trace refers to tracing software running on a separate target RISC-V
platform, via a trace control/data transport that provides external access to
the trace encoder controls cite:[ETrc].

These two extensions only affect debug and trace orchestrated by an external
actor - self-hosted debug (and trace) are managed directly by the RDSM.

This chapter refers to the Debug specification cite:[ExtDbg], Trace specification
cite:[ETrc], and the External debug security extension cite:[ExtDbgSec] for the
description and behavior of controls outside the scope of this specification,
but which interact with controls specified in this specification when one or
more supervisor domains are used.

[NOTE]
====
The configuration for `msdcfg.SEDA` and `msdcfg.SETA` is expected to
be obtained from the manifest/configuration of the supervisor domain and
reported in the attestation report for the supervisor domain and it's workloads.
The RDSM should manage this supervisor domain configuration state for context
switching using secure memory.

These configurations allow external debug and trace but do not enable them. If
external debug and/or trace is allowed for a supervisor doamin, an external
debugger may enable the external debug and/or trace for that supervisor domain.
====

=== `Smsdedbga`: External Debug allowed control for Supervisor Domain

When M-mode external debug is enabled, all supervisor domains may also be
debugged by an external debugger irrespective of the configuration held in
`msdcfg.SEDA`.

[NOTE]
====
Whether external debug of M-mode is permitted is determined by the hardware root
of trust (RoT) (cite:[TCGGL]) of the RDSM and is outside the scope of this
specification. When such debug is enabled, the RDSM itself is under debug, and
all supervisor domains managed by the RDSM are implicitly under debug as well.
====

When M-mode external debug is disabled, whether execution at privilege modes
less than `M` may be debugged by an external debugger depends on the
configuration held in `msdcfg.SEDA`, as described below:

When `msdcfg.SEDA` is 0:

* External debuggers are disallowed from accessing the memory or state of the
  currently active supervisor domain.
* Entry into Debug Mode from the currently active supervisor domain is
  disallowed.

When `msdcfg.SEDA` = 1, external debug of privilege modes less than `M` is
allowed for the currently active supervisor domain, subject to the additional
requirements listed below. +

. External debug must be able to access supervisor domain memory and state. In
  this context, "state" includes all supervisor domain resources defined as
  accessible by the Debug specification (cite:[ExtDbg]) for the currently active
  supervisor domain.
. Entry into Debug Mode from the currently active supervisor domain is allowed.

To enforce the above controls specified by this extension, the following
functional and security requirements must be met by the external secure debug
system cite:[ExtDbgSec]:

. External debug of M-mode can be enabled only by the HW RoT of the RDSM.
. The RDSM must be able to context switch all triggers even when `d-mode` = 1.
  This functional change allows the RDSM to remain in control of external debug
  for supervisor domains when it is not under external debug itself.

=== `Smsdetrca`: External Trace allowed control for Supervisor Domain

When M-mode external trace is enabled, all supervisor domains activity may also
be traced by an external trace tool irrespective of the configuration held in
`msdcfg.SETA`.

[NOTE]
====
Whether external tracing of M-mode is permitted is determined by the hardware
root of trust (RoT) (cite:[TCGGL]) of the RDSM and is outside the scope of this
specification. When such tracing is enabled, the RDSM itself is under debug, and
all supervisor domains managed by the RDSM are implicitly under debug as well.
====

When M-mode external trace is disabled, whether execution at privilege modes
less than M-mode may be traced by an external trace tool depends on the
configuration held in `msdcfg.SETA`, as described below:

When `msdcfg.SETA` = 0, external trace of the currently active supervisor domain
is disallowed.

When `msdcfg.SETA` = 1, external trace of privilege modes less than `M` is
allowed for the currently active supervisor domain, subject to the additional
requirements listed below.

. When M-mode external tracing is disabled, tracing must be stopped on:
.. Entry into Debug Mode
.. Entry into M-mode

To enforce the above controls specified by this extension, the following
functional and security requirements must be met by the external debug security
system cite:[ExtDbgSec]:

. External trace of M-mode can be enabled only by the HW RoT of the RDSM.

