[[chapter7]]
[[Smsdia]]
== Supervisor Domain Interrupt Assignment

Interrupts that occur during the execution of a supervisor domain cause a trap
to the RDSM in M-mode by default.

To increase performance, the RDSM can delegate the handling of certain
interrupts, like the timer interrupt or the local performance counter
overflow interrupt (LCOFI), to the supervisor domain by setting the
appropriate `mideleg` bits. This delegation could necessitate the RDSM to
context switch additional state related to such delegated interrupts,
including `stimecmp` and the HPM CSRs.

Additionally, the RDSM may assert a _virtual interrupt_ to a supervisor domain.
Such _virtual interrupts_ might be asserted as part of handling a real
interrupt, such as a RAS interrupt, or they may have no direct connection to
any actual interrupt event.

Some supervisor domains may have devices assigned to them for I/O operations.
Devices designed to carry out I/O operations typically signal the completion
of an I/O task or an associated error via an external interrupt. These external
interrupts might be aggregated and indicated by an interrupt controller linked
to the RDSM. The RDSM, in the course of handling an external interrupt, should
forward the interrupt to the relevant supervisor domain. The efficiency of
handling external interrupts by a supervisor domain can be enhanced if the
external interrupts could be directly assigned to the supervisor domain.

To accommodate such supervisor domains, this specification extends the IMSIC
and APLIC specified by the RISC-V Advanced Interrupt Architecture (AIA)
specification cite:[AIA] to support multiple _supervisor interrupt domains_,
enabling an individual _supervisor interrupt domain_ to be associated with each
such supervisor domain.

In some systems, a _supervisor interrupt domain_ in both an APLIC and an IMSIC
may be associated with a supervisor domain, with the supervisor interrupt domain
of the APLIC configured to route interrupts as MSIs to the corresponding
_supervisor interrupt domain_ of the IMSIC.

Interrupt controllers other than APLIC and/or IMSIC that support multiple
_supervisor interrupt domains_ may also serve a supervisor domain.

If there are N implemented _supervisor interrupt domains_, they are numbered
from 0 to N − 1, and the maximum implemented _supervisor interrupt domain
number_ is N − 1.

[[SD-IMSIC]]
=== IMSIC Extension for Supervisor Domains

The IMSIC is extended to support multiple _supervisor interrupt domains_, where
each _supervisor interrupt domain_ may be associated with a supervisor domain.
A _supervisor interrupt domain_ in an IMSIC consists of:

* A supervisor-level interrupt file.
* Optionally, one or more guest interrupt files.

Each _supervisor interrupt domain_ in an IMSIC is identified by a *supervisor
interrupt domain number* (`SIDN`).

When all harts are within a single _hart group_ as defined by cite:[AIA],
the memory-mapped address of the supervisor-level interrupt file for SIDN `n`
and hart `h`, is:

[latexmath]
++++
\text{Address} = B + n \times 2^I + h \times 2^D
++++

Constants `B` and `D` in this formula are specified by cite:[AIA], while `I`
is a new constant for supervisor interrupt domains. Constant `I` must be
>= `k + D`, where `k` is the number of bits needed to represent any hart
number `h`.

If the largest _supervisor interrupt domain_ number is stem:[n_{\text{max}}],
then `q` -- the number of bits needed to represent any _supervisor interrupt
domain_ number -- is defined as:

[latexmath]
++++
q = \lceil \log_2(n_{\text{max}} + 1) \rceil
++++

Address `B` must be aligned to a stem:[2^{q + I}] address boundary. (This
automatically makes `B` also aligned to a stem:[2^{k + D}] address boundary
as required by the existing cite:[AIA].)

When there are hart groups, the memory-mapped address of the supervisor-level
interrupt file for group `g`, SIDN `n`, and hart `h` within the group, is:

[latexmath]
++++
\text{Address} = g \times 2^E + B + n \times 2^I + h \times 2^D
++++

Constant `E` must be >= `max(k + C, q + I)`, but will usually be much larger.

The `Smsdia` extension (<<SDI>>) provides the mechanism to select a
_supervisor interrupt domain_ in an IMSIC as a source of supervisor-level and
guest external interrupts for a hart. The interrupt signal from the selected
_supervisor interrupt domain's_ supervisor-level interrupt file appears as bit
`SEIP` in `mip` and `sip`. The interrupt signals from any _guest interrupt
files_ of the selected supervisor interrupt domain appear as active bits in
the hypervisor CSR `hgeip`.

The `siselect` and `sireg` CSRs access the registers of the supervisor-level
interrupt file in the selected _supervisor interrupt domain_. If the selected
_supervisor interrupt domain_ implements _guest interrupt files_ then the
`vsiselect` and `vsireg` CSRs access the registers of a _guest interrupt file_,
of that _supervisor interrupt domain_, as determined by `hstatus.VGEIN`.

[[SD-APLIC]]
=== APLIC Extension for Supervisor Domains

The APLIC supports the concept of multiple interrupt domains where each
interrupt domain may be associated with a subset of RISC-V harts at one
privilege level. To support the Supervisor Domain use cases, the APLIC
must support multiple supervisor-level interrupt domains. A supervisor-level
interrupt domain in the APLIC may be then associated with a Supervisor Domain by
configuring it in _direct delivery mode_ or when the hart uses an IMSIC by
configuring it in _MSI delivery mode_.

To support supervisor domains in MSI delivery mode, the `smsiaddrcfgh` register
is extended with two new parameters called `DXS` (Domain Index Shift) and
`DXW` (Domain Index Width) to help determine the addresses to write outgoing
MSIs. The extended `smsiaddrcfgh` has the following format:

[literal]
....
    bits 28:24     DXS (WARL)
    bits 22:20     LHXS (WARL)
    bits 18:16     DXW (WARL)
    bits 11:0      High Base PPN (WARL)
....

Let `CI` be the Child Index from the `sourcecfg[i]` corresponding to an
interrupt source `_i_`. The MSI target address for this interrupt source
is then computed as follows:

[latexmath]
++++
n = \text{CI} \mathbin{\&} \left( 2^{\text{DXW}} - 1 \right)
\\
\text{MSI address} =
\left(
  \text{Base PPN}
  \mid ( n \ll \text{DXS} )
  \mid ( g \ll (\text{HHXS} + 12) )
  \mid ( h \ll \text{LHXS} )
  \mid \text{Guest Index}
\right) \ll 12
++++

The parameter `DXS` relates to the constant `I` specified in section <<SD-IMSIC>>
as: `DXS = (I - 12)`.

Refer to cite:[AIA] for the detailed definitions of constants `HHXS`, `g`, `h`,
`LHXS`, and Guest Index.

[[SDI]]
=== "Smsdia" : Standard Extension for Supervisor Domain Interrupt Assignment

The `Smsdia` extension adds supports to select a _supervisor interrupt domain_
in an interrupt controller as a source of supervisor-level and guest external
interrupts for a hart using the `msdcfg` CSR.

The RDSM needs a method to be alerted if an external interrupt, whether a
supervisor-level external interrupt or guest external interrupt, is pending for
any supervisor domains not currently active on a hart. The RDSM could leverage
this notification to inform its scheduling decisions. To facilitate this
functionality, the `Smsdia` extension introduces the `msideip` and `msideie`
CSRs, along with an local supervisor domain external interrupt (`LSDEI`).

==== Machine supervisor domain configuration (`msdcfg`)

The `msdcfg` is a 32-bit read/write register, formatted as shown in <<MSDCFG>>.

The `SIDN` field selects an interrupt domain among the plurality of
_supervisor interrupt domains_ associated with a hart as the active supervisor
interrupt domain for supervisor-level external interrupt and guest external
interrupts.

The `SIDN` field is a WLRL field that must be able to hold a value between 0
and the maximum implemented _supervisor interrupt domain number_, inclusive.
If there is only a single _supervisor interrupt domain_ connected to the hart,
then `SIDN` may be read-only zero.

When `SIDN` is not the number of an implemented _supervisor interrupt domain_
then the following rules apply:

* The supervisor-level external interrupt pending signal indicated in `mip.SEIP`
  is 0.
* All non-custom values of `siselect` that access IMSIC registers designate an
  _inaccessible_ register. When `siselect` holds the number of an _inaccessible_
  register, attempts from M-mode or HS-mode to access `sireg` raise an illegal
  instruction exception.
* Access to CSR `stopei` raises an illegal instruction exception.
* The `hstatus.vgein` field is read-only zero.
* `hgeip` is read-only 0.

When the _supervisor interrupt domain_ selected by `msdcfg.SIDN` is an
implemented, and is an IMSIC, the following rules apply:

* The supervisor-level external interrupt pending signal of supervisor-level
  interrupt file of the selected _supervisor interrupt domain_ is indicated in
  `mip.SEIP`.
* The `siselect` and `stopei` CSRs operate on the registers of the
  supervisor-level interrupt file in the selected _supervisor interrupt
  domain_.
* The guest external interrupt pending signals of the _guest interrupt files_
  of selected _supervisor interrupt domain_ are indicated in the `hgeip` CSR.
* The `hstatus.VGEIN` selects a _guest interrupt file_ in the selected supervisor
  interrupt domain and `vsiselect` and `vstopei` CSRs operate on the registers
  of the corresponding _guest interrupt file_.

When the _supervisor interrupt domain_ selected by `msdcfg.SIDN` is implemented,
and is an APLIC, the following rules apply:

* The supervisor-level external interrupt pending signal of the selected APLIC
  _supervisor interrupt domain_ is indicated in `mip.SEIP`.

[NOTE]
====
The `Smsdia` extension provides for directly associating a _supervisor interrupt
domain_ with up to 64 supervisor domains. The RDSM may emulate interrupt
controllers for additional supervisor domains.

To emulate an IMSIC _supervisor interrupt domain_, the RDSM may use the illegal
instruction trap facilitated by AIA-added state-enbale bits to
`mstateen0/mstateen0h` for emulation purposes.
====

==== Hypervisor Guest External Interrupt Registers (`hgeip` and `hgeie`)

When the H extension is also implemented, the implementation must internally
maintain an array of registers that hold the state of the `hgeip` and `hgeie`
CSRs, with one pair of registers per implemented supervisor interrupt domain
number. The `hgeip` and `hgeie` CSRs access the element of this array
corresponding to the value of `msdcfg.SIDN`.

==== Machine supervisor interrupt domain external interrupt pending (`msideip/msideiph`)

The `msideip` is a 64-bit read-only register, formatted as shown in <<MSDEIP>>.
When MXLEN=32, `msideiph` is a 32-bit read-only register which aliases bits
63:32 of `msideip`. When MXLEN=64, `msideiph` does not exist.

[[MSDEIP]]
.`msideip` register

[wavedrom, , ]
....
{reg: [
  {bits: 64, name: 'Interrupts'},
], config:{lanes: 1, hspace:1024}}
....

Each bit __i__ in the register summarizes the external interrupts pending in the
_supervisor interrupt domain_ numbered __i__.

When the _supervisor interrupt domain_ identified by __i__ is implemented by an
APLIC, the bit __i__ indicates the state of the supervisor-level external interrupt
pending signal provided by the _supervisor interrupt domain_ in that APLIC.

When the _supervisor interrupt domain_ identified by __i__ is implemented by an
IMSIC, bit __i__ must be set to one if and only if either of the following
conditions holds:

* the SEIP signal for _supervisor interrupt domain_ __i__ is asserted; or
* the bitwise logical AND of the internal `hgeip` and `hgeie` registers for
  _supervisor interrupt domain_ __i__ is nonzero (i.e., the value that SGEIP
  would have for that domain).

The summary of external interrupts pending in a _supervisor interrupt domain_ is
visible in the `msideip` register even when `msdcfg.SIDN` is not the valid number
of an implemented _supervisor interrupt domain_.

==== Machine supervisor domain external interrupt enable (`msideie/msideieh`)
The `msideie` is a 64-bit read-write register, formatted as shown in <<MSDEIE>>.
When MXLEN=32, `msideieh` is a 32-bit read-write register which aliases bits
63:32 of `msideie`. When MXLEN=64, `msideieh` does not exist.

[[MSDEIE]]
.`msideie` register

[wavedrom, , ]
....
{reg: [
  {bits:  1, name: '0'},
  {bits: 63, name: 'Interrupts (WARL)'},
], config:{lanes: 1, hspace:1024}}
....

The `msideie` CSR selects the subset of _supervisor interrupt domains_ that cause
a local supervisor domain external interrupt. The enable bits in `msideie` do not
affect the supervisor-level external interrupt and guest external interrupt
pending signals from the _supervisor interrupt domain_ selected by `msdcfg.SIDN`.

==== Machine and Supervisor Interrupt registers (`mip/mie` and `sip/sie`)

The `Smsdia` extension introduces the local supervisor domain external
interrupt (`LSDEI`). This interrupt is treated as a standard local
interrupt that is assigned to bit TBA in the `mip`, `mie`, `sip`, and `sie`
registers. The bit TBA in `mip` and `sip` is called `LSDEIP` and the same bit in
`mie` and `sie` is called `LSDEIE`. The `mideleg` register controls the
delegation of `LSDEI` to S-mode. This interrupt cannot be delegated to
VS-mode and bit TBA of `hideleg` is read-only zero.

The `mip.LSDEIP` bit read-only and is set to 1 if the bitwise logical AND of CSRs
`msideip` and `msideie` is nonzero in any bit. The `mie.LSDEIE` bit is writable.

When bit TBA of `mideleg` is zero, `sip.LSDEIP` and `sie.LSDEIE` are read-only
zeros. Else, `sip.LSDEIP` and `sie.LSDEIE` are aliases of `mip.LSDEIP` and
`mie.LSDEIE`.

Multiple simultaneous interrupts destined for different privilege modes are
handled in decreasing order of destined privilege mode. Multiple simultaneous
interrupts destined for the same privilege mode are handled in the following
decreasing default priority order: high-priority RAS event, MEI, MSI, MTI,
LSDEI, SEI, SSI, STI, SGEI, VSEI, VSSI, VSTI, LCOFI, low-priority RAS event.

[NOTE]
====
The RDSM may use the local supervisor domain external interrupt to determine if
a supervisor domain has become ready to run since it was last descheduled. When
a supervisor domain that has a supervisor domain interrupt controller directly
assigned to it, the RDSM updates the `msdcfg.SIDN` to select that supervisor
interrupt domain and may clear the bit corresponding to that supervisor
interrupt domain in `msideie` prior to resuming execution of the supervisor
domain.

The RDSM may delegate `LSDEI` to a supervisor domain that may be entrusted by
the RDSM to get notified about supervisor domain external interrupts pending for
one or more other supervisor domains. Typically, this use case involves a single
supervisor domain that is trusted by the RDSM to receive such notifications. The
delegation supports optimizing the exit sequence from such supervisor domain by
enabling such supervisor domains to voluntarily yield execution in response to
pending interrupts for the other supervisor domains.
====

=== "Smifdeleg" : Standard Extension for Delegation of IMSIC Interrupt Files

The `Smifdeleg` extension enables delegating a subset of the interrupt
files within a _supervisor interrupt domain_ in an IMSIC to a supervisor domain.

The `Smifdeleg` extension depends on the `Smaia` extension.

To support delegation, this extension introduces an 64-bit read-write
register named `mifd`, formatted as shown in <<MIFD>>. When MXLEN=32, `mifdh` is
a 32-bit read-write register that aliases bits 63:32 of `mifd`.  When MXLEN=64,
the `mifdh` register does not exist.

[[MIFD]]
.`mifd` register

[wavedrom, , ]
....
{reg: [
  {bits:  1, name: 'S'},
  {bits: 63, name: 'GIF (WARL)'},
], config:{lanes: 1, hspace:1024}}
....

The `S` bit when set to 1 enables access to the supervisor-level interrupt file
in the _supervisor interrupt domain_ selected by `msdcfg.SIDN`.

If the H extension is also implemented, then each bit of the `GIRF` field when
set to 1 enables access to the _guest interrupt files_ in the supervisor
interrupt domain selected by `msdcfg.SIDN`. If `GEILEN` is nonzero, bit
`GEILEN:1` shall be writeable in `mifd`, and all other bit positions of the
`GIRF` field shall be read-only zeros.

If the `S` bit of `mifd` is 1 and the _supervisor interrupt domain_ selected by
`msdcfg.SIDN` is implemented then:

* The supervisor-level external interrupt pending signal of supervisor-level
  interrupt file of the selected _supervisor interrupt domain_ is indicated in
  `mip.SEIP`.
* The `siselect`, `sireg`, and `stopei` CSRs operate on the registers of the
  supervisor-level interrupt file in the selected _supervisor interrupt
  domain_.

If the `S` bit of `mifd` is 0 or the _supervisor interrupt domain_ selected by
`msdcfg.SIDN` is not implemented then:

* The supervisor-level external interrupt pending signal indicated in `mip.SEIP`
  is 0.
* All non-custom values of `siselect` that access IMSIC registers designate an
  _inaccessible_ register. When `siselect` holds the number of an _inaccessible_
  register, attempts from M-mode or S/HS-mode to access `sireg` raise an illegal
  instruction exception.
* Access to `stopei` from M-mode or S/HS-mode raises an illegal instruction
  exception.

If the hypervisor extension is also implemented and the _supervisor interrupt
domain_ selected by `msdcfg.SIDN` is implemented then:

* The guest external interrupt pending signals of the _guest interrupt files_
  of the selected _supervisor interrupt domain_ are indicated in the `hgeip` CSR
  if the bit corresponding to their guest external interrupt number in `mifd`
  is 1 else they are indicated as 0.

* Bits `GEILEN:1` of `hgeie` are writable if the bit at same position in `mifd`
  is 1. All other bits of `hgeie` are read-only zeroes.

* If `hstatus.VGEIN` is not 0 and the bit selected by `VGEIN` in `mifd` is 1
  then the `vsiselect`, `vsireg`, and `vstopei` CSRs operate on the registers of
  the _guest interrupt file_ selected by `VGEIN`. If `VGEIN` is 0 or the the bit
  selected by `VGEIN` in `mifd` is 0 then the `vsiselect`, `vsireg`, and
  `vstopei` CSRs operate as-if the `VGEIN` is the number of an unimplemented
  guest external interrupt.

If the hypervisor extension is also implemented and the _supervisor interrupt
domain_ selected by `msdcfg.SIDN` is not implemented then:

* The `hgeip` and `hgeie` CSRs are read-only zeros.

* The `vsiselect`, `vsireg`, and `vstopei` CSRs operate as-if the `VGEIN` is the
  number of an unimplemented guest external interrupt for all values of `VGEIN`.

When `Smifdeleg` is implemented, `hip.SGEIP` is 1 if and only if the bitwise
logical-AND of CSRs `hgeip`, `hgeie`, and `mifd` is nonzero in any bit.

When `Smifdeleg` is implemented, the `msideip` bit corresponding to _supervisor
interrupt domain_ identified by `msdcfg.SIDN` is the logical OR of the interrupt
signals from the interrupt files of that _supervisor interrupt domain_ that are
not delegated by `mifd`. Bits of `msideip` corresponding to all other
_supervisor interrupt domains_ are the logical OR of all the interrupt signals
from the corresponding _supervisor interrupt domain_ in the IMSIC.

[NOTE]
====
The `Smifdeleg` is intended to be used to delegate interrupt files to
enlightened (a.k.a. para-virtualized) supervisor domains. Usually, one of the
supervisor domains participating in the delegation is a donor domain that
initially has access to all the interrupt files.

Such a donor supervisor domain may then donate, either temporarily or
permanently, one or more of the interrupt files (usually _guest
interrupt files_) to a recipient supervisor domain by invoking SBI functions
provided by the RDSM. The donor domain does not expect to access the donated
interrupt files once they have been delegated by the RDSM to the recipient
domain.

The recipient domains must not assume the donated interrupt files are
contiguously laid out in memory, nor expect the corresponding bits in `hgeip`
and `hgeie` to be contiguous, nor expect to use a supervisor-level interrupt
file.

The memory locations of the delegated interrupt files and their guest external
interrupt numbers are provided to the recipient supervisor domains by the RDSM
through software mechanisms such as SBI.
====

