[[chapter4]]
[[Smmpt]]
== Machine-mode Memory Protection Table (MPT)

Memory Protection table is a radix-tree table used to provide read, write, and
execute permissions for implicit and explicit memory accesses by effective
privilege modes less than M.

The following MPT extensions are defined:

MPT extensions with read-write-execute access permissions:

* Smmpt34 - Page-based 34-bit memory protection system (RV32 only)
* Smmpt43 - Page-based 43-bit memory protection system (RV64 only)
* Smmpt52 - Page-based 52-bit memory protection system (RV64 only)
* Smmpt64 - Page-based 64-bit memory protection system (RV64 only)

MPT extensions with 1-bit access permission:

* Smmpt1bp34 - Page-based 34-bit memory protection system with 1-bit
  permission (RV32 only)
* Smmpt1bp44 - Page-based 44-bit memory protection system with 1-bit
permission (RV64 only)
* Smmpt1bp53 - Page-based 53-bit memory protection system with 1-bit
permission (RV64 only)
* Smmpt1bp64 - Page-based 64-bit memory protection system with 1-bit
permission (RV64 only)

MPT NAPOT extensions

* Smmptnapot - NAPOT Access-Type Permission Granularity (RV32 and R64)
* Smmptnlnapot - NAPOT Memory Protection Table (RV64 only)

These MPT extensions depend on `Smsdid`.
Smmpt34, Smmpt43, Smmpt52 and Smmpt64 depend on `Smmptnapot`.
Smmpt1bp34, Smmpt1bp44, Smmpt1bp53, Smmpt1bp64 depend on `Smmptnapot`.

=== Smmpt34: Page-Based Memory Protection System

The RV32 Memory Protection Table provides memory access type permissions
for pages in a 34-bit supervisor physical address (SPA) space. The SPA is
partitioned into a page number (`pn`) and a range offset. When the Smmpt34 mode
is selected in the `MODE` field of `mmpt`, the access type permissions for a
supervisor physical address are determined using a two-level memory protection
table.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="RV32 Supervisor Physical Address", id=rv32-spa]
[wavedrom, ,svg]
....
{reg: [
  {bits:  15, name: 'range offset', attr: '15'},
  {bits:  10, name: 'pn[0]',        attr: '10' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The root memory protection table has 2^9^ memory-protection-table entries
(MPTEs) and the memory protection tables linked to the root table have 2^10^
MPTEs. Each MPTE is a four byte value. Each memory protection table,
including the root MPT, must always be aligned to a page boundary.

If the MPTE points to the next level of the memory protection table, it is a
non-leaf MPTE, else it is a leaf MPTE. A leaf MPTE provides access type
permissions for eight pages in the address range determined by that MPTE.

The format of a non-leaf MPTE entry is shown in <<rv32-mpte>> and that of a leaf
MPTE entry in <<rv32-mpte-leaf>>.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="`Smmpt34` non-leaf `MPTE`", id="rv32-mpte"]
[wavedrom, ,svg]
....
{reg: [
  {bits:  1,  name: 'V'},
  {bits:  1,  name: 'L=0'},
  {bits:  8,  name: 'RESERVED'},
  {bits:  22, name: 'PPN'},
], config:{lanes: 2, hspace:1024}}
....

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="`Smmpt34` leaf `MPTE`", id="rv32-mpte-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:  1,  name: 'V'},
  {bits:  1,  name: 'L=1'},
  {bits:  5,  name: 'RESERVED'},
  {bits:  24, name: 'PERMS'},
  {bits:  1,  name: 'N'},
], config:{lanes: 2, hspace:1024}}
....

The `V` bit indicates if the MPTE is valid; if it is 0, all other bits in the
MPTE are don't-cares and may be used freely by software. When the `MPTE` is
valid, the bits constituting the `RESERVED` field are reserved for future
standard use and, until its use is defined by some standard extension,
must be zeroed by software for forward compatibility. If any of these
bits are set, an access-fault exception is raised.

Explicit stores by a hart that update the `V` bit of leaf and/or non-leaf MPTEs
from 0 to 1 and are visible to a hart will eventually become visible within a
bounded timeframe to subsequent implicit accesses by that hart to such MPTEs.

[NOTE]
====
This behavior relieves M-mode software from executing certain memory-management
instructions, such as MFENCE.SPA or MINVAL.SPA, which would normally be used to
synchronize the hart’s MPT caches when a memory-resident MPTE is changed from
Invalid to Valid. Synchronizing the hart’s MPT caches with other forms of updates
to a memory-resident MPTE, including when a MPTE is changed from Valid to Invalid,
requires the use of suitable memory-management instructions. This behavior
guarantees that a change to a MPTE from Invalid to Valid is made visible within a
bounded time, thereby making the execution of these memory-management
instructions redundant. The performance benefit of eliding these instructions
outweighs the cost of an occasional gratuitous additional access fault that may occur.

Depending on the microarchitecture, some possible ways to facilitate include:
not storing Invalid PTEs in the MPT page-walk caches, automatically evicting
Invalid MPTEs using a bounded timer, or making MPT page-walk caches coherent
with store instructions that modify MPTEs.
====

When the `L` bit is set to 0, the entry is a non-leaf MPTE, else it is a leaf MPTE.

A non-leaf MPTE holds the PPN of the next level of the memory protection table.

A leaf MPTE holds eight tuples of access type permisssion bits - one for each
page in the range determined by that MPTE. Each tuple consists of 3 bits `XWR`,
that provide the Execute (`X`), Write (`W`), and Read (`R`) permissions. The most
significant 3 bits of the range offset identify a page in that range and are
used to identify the access type permission bits for an access to that page.

[[Smmpt-xwr-encoding]]
.Encoding of `MPTE` X/W/R permission tuple
[%autowidth,float="center",align="center",cols="^,^,^,<",options="header"]
|===
| X | W | R | Meaning
| 0 | 0 | 0 | _Reserved for future use._
| 0 | 0 | 1 | Read-only page.
| 0 | 1 | 0 | _Reserved for future use._
| 0 | 1 | 1 | Read-write page.
| 1 | 0 | 0 | Execute-only page.
| 1 | 0 | 1 | Read-execute page.
| 1 | 1 | 0 | _Reserved for future use._
| 1 | 1 | 1 | Read-write-execute page.
|===

Access type permissions -- readable, writable, or executble -- are checked
by MPT the same as for VS-stage and G-stage translation. For a memory access
made to support VS-stage or G-stage address translation (such as a read/write to
a VS-stage page table or a G-stage page table), permissions are checked as
though for an implicit load or store, not for the original access type. However,
any exception is always reported for the original access type (instruction,
load, or store/AMO).

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt34 supports 32 MiB megapages.

=== Smmpt1bp34: Page-Based Memory Protection System with 1-bit permission

The RV32 Memory Protection Table provides 1-bit memory access permission for
pages in a 34-bit supervisor physical address (SPA) space. The SPA is
partitioned into a page number (`pn`) and a range offset. When the Smmpt1bp34
mode is selected in the `MODE` field of `mmpt`, the access type permissions for
a supervisor physical address are determined using a two-level memory
protection table.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="RV32 Supervisor Physical Address", id=rv32-spa-1bp]
[wavedrom, ,svg]
....
{reg: [
  {bits:  16, name: 'range offset', attr: '16'},
  {bits:  10, name: 'pn[0]',        attr: '10' },
  {bits:  8,  name: 'pn[1]',        attr: '8'},
], config:{lanes: 1, hspace:1024}}
....

The root memory protection table has 2^8^ memory-protection-table entries
(MPTEs) and the memory protection tables linked to the root table have 2^10^
MPTEs. Each MPTE is a four byte value. Each memory protection table,
including the root MPT, must always be aligned to a page boundary.

If the MPTE points to the next level of the memory protection table, it is a
non-leaf MPTE, else it is a leaf MPTE. A leaf MPTE provides 1-bit access
permission for sixteen pages in the address range determined by that MPTE. When
the permission bit is 1, read, write and execute access are permitted; When the
permission bit is 0, read, write and execute access is not permitted.

The format of a non-leaf MPTE entry is shown in <<rv32-mpte>> and that of a leaf
MPTE entry in <<rv32-mpte-1bp-leaf>>.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="`Smmpt1bp34` leaf `MPTE`", id="rv32-mpte-1bp-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'V'},
  {bits:  1, name: 'L=1'},
  {bits:  5, name: 'RESERVED'},
  {bits: 16, name: 'PERMS'},
  {bits:  8, name: 'RESERVED'},
  {bits:  1, name: 'N'},
], config:{lanes: 2, hspace:1024}}
....

Specification of the `V`, `RESERVED` and `L` bit is the same as <<Smmpt34>>.

A leaf `Smmpt1bp34` MPTE holds sixteen 1-bit permission bits - one for each
page in the range determined by that MPTE. When this bit is 1, the MPT provides
read, write, and execute permissions and when the bit is 0, read, write, and
execute access are all not permitted. The most significant 4 bits of the range
offset identify a page in that range and are used to identify the 1-bit access
permission for an access to that page.

Access permission check rules are the same as <<Smmpt34>>.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt1bp34 supports 64 MiB megapages.

[[MPT_ACC_LKUP]]
==== MPT access type permissions lookup process
Access type permissions for a physical address PA are determined as
follows:

1. Let _a_ be `mmpt.ppn` x PAGESIZE, and let _i_ = LEVELS-1 (For Smmpt34,
   PAGESIZE is 2^12^ and LEVELS=2). The `mmpt` register must be active,
   i.e., the effective privilege mode must not be M-mode.

2. Let _mpte_ be the value of the `MPTE` at address _a_ + _pa.pn[i]_
   x MPTESIZE (For Smmpt34, MPTESIZE=4). If accessing _mpte_ violates a PMA
   or PMP check, raise an access-fault exception corresponding to the original
   access type.

3. If _mpte.v_=0, or if any bits or encodings that are reserved for future
   standard use are set within _mpte_, stop and raise an access-fault exception
   corresponding to the original access type.

4. Otherwise, the _mpte_ is valid. If _mpte.L=1_ go to step 5; Otherwise, this
   MPTE is a pointer to the next level of the memory protection table. Let
   _i_=_i_-1. If _i_<0, stop and raise an access-fault exception corresponding
   to the original access type. Otherwise, let _a_ = _mpte.PPN_ x PAGESIZE and
   go to step 2.

5. A leaf _mpte_ has been found. If i > 0, the bits _pa.pn[i-1]_ are included
   in the range offset, else for i = 0, the range offset is specified in the
   _pa_. Let _pi_ be the NUMPGINRANGE (For Smmpt34, NUMPGINRANGE is 3; For
   Smmpt1bp34, NUMPGINRANGE is 4) most significant bits of the range offset.
   Let _perms=PERMS[pi*3+2:pi*3]_ for Smmpt[34|43|52|64]; _perms=PERMS[pi]_ for
   Smmpt1bp[34|44|53|64]. Determine if the requested memory access is permitted
   by the _perms_ bits, given the effective privilege mode and MXR field of the
   `mstatus` register. If not, stop and raise an access-fault exception
   corresponding to the original access type, else the requested memory access
   is permitted.

Implicit accesses to MPT by this process are checked by PMP/Smepmp as implicit
M-mode accesses. The endianness of such implicit accesses is controlled by
`mstatus.MBE`.

=== Smmpt43: Page-Based 43-bit Memory Protection System

This section describes a page-based memory protection system for RV64, which
supports a 43-bit supervisor physical address space. The design of Smmpt43
follows the overall scheme of Smmpt34, and this section details only the
differences between the schemes.

[NOTE]
====
Multiple memory protection systems are specified for RV64 to relieve the tension
between providing a large physical address space and minimizing the memory
protection cost. For many systems, 43-bits of physical address space is ample,
and so Smmpt43 suffices. Smmpt52 increases the physical address space to 52
bits, but increases the physical memory capacity dedicated to memory protection
tables and the latency of memory protection table traversals. Smmpt64 increases
the physical address space to 64 bits.
====

Smmpt43 supports a 43-bit physical address space, divided into pages. The
Smmpt43 address is partitioned as shown in  <<rv64-spa-Smmpt43>>. The system
physical address must have bits 43 and higher all equal to 0, or else an
access-fault exception corresponding to the original access type will occur. The
Smmpt43 memory protection table has three levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt43 Supervisor Physical Address", id=rv64-spa-Smmpt43]
[wavedrom, ,svg]
....
{reg: [
  {bits:  16, name: 'range offset', attr: '16'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt43 memory protection tables contain 2^9^ memory protection table
entries (MPTEs). Each Smmpt43 MPTE is an eight byte value. A page table is
exactly the size of a page and must always be aligned to a page boundary.
The physical page number of the root memory protection table is stored in the
`mmpt` register's PPN field.

The format of a non-leaf MPTE entry is shown in <<rv64-mpte>> and that of a leaf
MPTE entry in <<rv64-mpte-leaf>>.

A leaf MPTE provides access type permissions for sixteen pages in the address
range determined by that MPTE.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt43 non-leaf `MPTE` entry", id="rv64-mpte"]
[wavedrom, ,svg]
....
{reg: [
  {bits:   1, name: 'V'},
  {bits:   1, name: 'L=0'},
  {bits:   8, name: 'RESERVED'},
  {bits:  52, name: 'PPN'},
  {bits:   1, name: 'RSV'},
  {bits:   1, name: 'N'},
], config:{lanes: 2, hspace:1024}}
....

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt43 leaf `MPTE` entry", id="rv64-mpte-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:   1, name: 'V'},
  {bits:   1, name: 'L=1'},
  {bits:   8, name: 'RESERVED'},
  {bits:  48, name: 'PERMS'},
  {bits:   5, name: 'RESERVED'},
  {bits:   1, name: 'N'},
], config:{lanes: 2, hspace:1024}}
....

If Smmptnlnapot is not implemented, bit 63 in a non-leaf MPTE remains reserved.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt43 supports 32 MiB _megapages_, 16 GiB
_gigapages_, and 8 TB _terapages_.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 3, MPTESIZE equals 8, and NUMPGINRANGE
equals 4.

=== Smmpt1bp44: Page-Based 44-bit Memory Protection System with 1-bit permission

This section describes a page-based memory protection system for RV64, which
supports a 44-bit supervisor physical address space. The design of Smmpt1bp44
follows the overall scheme of Smmpt1bp34, and this section details only the
differences between the schemes.

Smmpt1bp44 supports a 44-bit physical address space, divided into pages. The
Smmpt1bp44 address is partitioned as shown in  <<rv64-spa-Smmpt43>>. The system
physical address must have bits 44 and higher all equal to 0, or else an
access-fault exception corresponding to the original access type will occur. The
Smmpt1bp44 memory protection table has three levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt1bp44 Supervisor Physical Address", id=rv64-spa-Smmpt1bp44]
[wavedrom, ,svg]
....
{reg: [
  {bits:  17, name: 'range offset', attr: '17'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt1bp44 memory protection tables contain 2^9^ memory protection table
entries (MPTEs). Each Smmpt1bp44 MPTE is an eight byte value. A page table is
exactly the size of a page and must always be aligned to a page boundary.
The physical page number of the root memory protection table is stored in the
`mmpt` register's PPN field.

The format of a non-leaf MPTE entry is shown in <<rv64-mpte>> and that of a leaf
MPTE entry in <<rv64-mpte-1bp-leaf>>.

A leaf MPTE provides access type permissions for thirty two pages in the address
range determined by that MPTE.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt1bp44 leaf `MPTE` entry", id="rv64-mpte-1bp-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:   1, name: 'V'},
  {bits:   1, name: 'L=1'},
  {bits:  24, name: 'RESERVED'},
  {bits:  32, name: 'PERMS'},
  {bits:   5, name: 'RESERVED'},
  {bits:   1, name: 'N'},
], config:{lanes: 2, hspace:1024}}
....

If Smmptnlnapot is not implemented, bit 63 in a non-leaf MPTE remains reserved.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt1bp44 supports 64 MiB _megapages_, 32 GiB
_gigapages_, and 16 TB _terapages_.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 3, MPTESIZE equals 8, and NUMPGINRANGE
equals 5.

=== Smmpt52: Page-Based 52-bit Memory Protection System

This section describes a page-based memory protection system for RV64 that
supports 52-bit physical address spaces. It closely follows the design of
Smmpt43, simply adding an additional level of page table, and so this section
only details the differences between the two schemes.

Smmpt52 supports a 52-bit physical address space, divided into pages. The
Smmpt52 address is partitioned as shown in  <<rv64-spa-Smmpt52>>. The system
physical address must have bits 52 and higher all equal to 0, or else an
access-fault exception corresponding to the original access type will occur. The
Smmpt52 memory protection table has four levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt52 Supervisor Physical Address", id=rv64-spa-Smmpt52]
[wavedrom, ,svg]
....
{reg: [
  {bits:  16, name: 'range offset', attr: '16'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
  {bits:  9,  name: 'pn[3]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt52 memory protection tables contain 2^9^ memory protection table
entries (MPTEs). Each MPTE is an eight byte value. A page table is exactly the
size of a page and must always be aligned to a page boundary. The physical page
number of the root memory protection table is stored in the `mmpt` register's
PPN field.

The MPTE formats for Smmpt52 are identical to that of Smmpt43.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt52 supports 32 MiB _megapages_, 16 GiB
_gigapages_, 8 TB _terapages_, and 4 PB _petapages_.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 4, MPTESIZE equals 8, and NUMPGINRANGE
equals 4.

=== Smmpt1bp53: Page-Based 53-bit Memory Protection System with 1-bit permission

This section describes a page-based memory protection system for RV64 that
supports 53-bit physical address spaces. It closely follows the design of
Smmpt1bp44, simply adding an additional level of page table, and so this section
only details the differences between the two schemes.

Smmpt1bp53 supports a 53-bit physical address space, divided into pages. The
Smmpt1bp53 address is partitioned as shown in  <<rv64-spa-Smmpt1bp53>>. The
system physical address must have bits 53 and higher all equal to 0, or else an
access-fault exception corresponding to the original access type will occur. The
Smmpt1bp53 memory protection table has four levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt1bp53 Supervisor Physical Address", id=rv64-spa-Smmpt1bp53]
[wavedrom, ,svg]
....
{reg: [
  {bits:  17, name: 'range offset', attr: '17'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
  {bits:  9,  name: 'pn[3]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt1bp53 memory protection tables contain 2^9^ memory protection table
entries (MPTEs). Each MPTE is an eight byte value. A page table is exactly the
size of a page and must always be aligned to a page boundary. The physical page
number of the root memory protection table is stored in the `mmpt` register's
PPN field.

The MPTE formats for Smmpt1bp53 are identical to that of Smmpt1bp44.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt1bp53 supports 64 MiB _megapages_, 32 GiB
_gigapages_, 16 TB _terapages_, and 8 PB _petapages_.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 4, MPTESIZE equals 8, and NUMPGINRANGE
equals 5.

=== Smmpt64: Page-Based 64-bit Memory Protection System

This section describes a page-based memory protection system for RV64 that
supports 64-bit physical address spaces. It closely follows the design of
Smmpt52, simply adding an additional level of page table, and so this section
only details the differences between the two schemes.

Smmpt64 supports a 64-bit physical address space, divided into pages. The
Smmpt64 address is partitioned as shown in  <<rv64-spa-Smmpt64>>. The
Smmpt64 memory protection table has five levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt64 Supervisor Physical Address", id=rv64-spa-Smmpt64]
[wavedrom, ,svg]
....
{reg: [
  {bits:  16, name: 'range offset', attr: '16'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
  {bits:  9,  name: 'pn[3]',        attr: '9'},
  {bits:  12, name: 'pn[4]',        attr: '12'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt64 root memory protection table contain 2^12^ memory protection
table entries (MPTEs). Each MPTE is an eight bytes value. The root memory
protection table is 32 KiB instead of the usual 4 KiB and must be aligned to a
32 KiB boundary. The physical page number of the root memory protection table is
stored in the `mmpt` register's PPN field.

The non-root Smmpt64 memory protection tables contain 2^9^ MPTEs, eight bytes
each. The non-root memory protection table is exactly the size of a page and
must always be aligned to a page boundary.

The MPTE formats for Smmpt64 are identical to that of Smmpt52.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt54 supports 32 MiB _megapages_, 16 GiB
_gigapages_, 8 TB _terapages_, 4 PB _petapages_, and 2 EB _exapages_.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 5, MPTESIZE equals 8, and NUMPGINRANGE
equals 4.

=== Smmpt1bp64: Page-Based 64-bit Memory Protection System

This section describes a page-based memory protection system for RV64 that
supports 64-bit physical address spaces. It closely follows the design of
Smmpt1bp53, simply adding an additional level of page table, and so this section
only details the differences between the two schemes.

Smmpt1bp64 supports a 64-bit physical address space, divided into pages. The
Smmpt1bp64 address is partitioned as shown in  <<rv64-spa-Smmpt1bp64>>. The
Smmpt1bp64 memory protection table has five levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt1bp64 Supervisor Physical Address", id=rv64-spa-Smmpt1bp64]
[wavedrom, ,svg]
....
{reg: [
  {bits:  17, name: 'range offset', attr: '17'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
  {bits:  9,  name: 'pn[3]',        attr: '9'},
  {bits:  11, name: 'pn[4]',        attr: '11'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt1bp64 root memory protection table contain 2^11^ memory protection
table entries (MPTEs). Each MPTE is an eight bytes value. The root memory
protection table is 16 KiB instead of the usual 4 KiB and must be aligned to a
16 KiB boundary. The physical page number of the root memory protection table is
stored in the `mmpt` register's PPN field.

The non-root Smmpt1bp64 memory protection tables contain 2^9^ MPTEs, eight bytes
each. The non-root memory protection table is exactly the size of a page and
must always be aligned to a page boundary.

The MPTE formats for Smmpt1bp64 are identical to that of Smmpt1bp53.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt1bp64 supports 64 MiB _megapages_, 32 GiB
_gigapages_, 16 TB _terapages_, 8 PB _petapages_, and 4 EB _exapages_.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 5, MPTESIZE equals 8, and NUMPGINRANGE
equals 5.

=== Smmptnapot - NAPOT Access-Type Permission Granularity

When `MPTE.L`=1 and `MPTE.N`=1, the leaf `MPTE` represents a memory protection
range that is part of a larger contiguous NAPOT memory protection range comprised
of 512 pages for RV64 and 1024 pages for RV32. All leaf MPTEs at that level of
this NAPOT memory protection range have the same value for L, N, PERMS and V
bits. Thus, the access permissions in the PERMS field of such
PTEs are identical.

Such MPTEs behave identically to leaf MPTEs in the MPT access permission lookup
process described in <<MPT_ACC_LKUP>>, except that:

* For RV32, the `N` bit may be set to 1 in the level 0 leaf MPTEs.
* For RV64, the `N` bit may be set to 1 in the leaf MPTEs.

[NOTE]
====
The motivation of NAPOT MPTE is that access-type permissions for one or more
entries representing the contigous region may be cached as a single cache entry
as if it were a single (large) page. This compaction can relieve access-type
permission caches. The scheme allows an implementation to not take advantage of
this property and simply cache the access-type permissions for pages seperately.

The scheme supports caching a single access-type permission entry representing a
2 MiB or a 1 GiB memory range for RV64. For RV32, it supports caching a single
access-type permission entry representing a 4 MiB memory range. These contigous
memory range sizes represent large/huge page sizes used commonly by memory
allocators.

A single MPTE entry covers a 64 KiB address range, so a separate 64 KiB NAPOT
PTE is not needed. One MPTE with all permissions being identical provides
the 64 KiB region support.
====

If Smmptnapot extension is implemented then one of Smmpt34, Smmpt1bp34, Smmpt43,
Smmpt1bp44, Smmpt52, Smmpt1bpt53, Smmpt64 or Smmpt1bp64 extensions must be
implemented.

=== Smmptnlnapot - NAPOT Memory Protection Table

The Smmptnlnapot extension supports NAPOT non-leaf MPTEs. This extension is
RV64 only, and depends on one of Smmpt43, Smmpt1bp44, Smmpt52, Smmpt1bp53,
Smmpt1bp64 or Smmpt64.

For RV64, when the `MPTE.L`=0 and `MPTE.N`=1, the non-leaf `MPTE`
is part of a range of MPTEs at that level of MPT with the same value for
the L, N, PPN, and V bits.

The following Non-leaf `MPTE` encodings are defined when _mpte_.N is 1.

[[Smmpt-napot]]
.Non-leaf `MPTE` encodings when _mpte_.N=1
[width="100%",cols="10%,30%,30%,30%",options="header",]
|===
| *_i_* a| *_mpte.PPN[8:0]_* a| *Description* a| *_mpte.napot_bits_*
|    0  a|       x xxxx xxxx a| Reserved      a| -
|  > 0  a|       x xxxx xxx1 a| Reserved      a| -
|  > 0  a|       x xxxx xx1x a| Reserved      a| -
|  > 0  a|       x xxxx x1xx a| Reserved      a| -
|  > 0  a|       x xxxx 1xxx a| Reserved      a| -
|  > 0  a|       x xxx1 xxxx a| Reserved      a| -
|  > 0  a|       x xx1x xxxx a| Reserved      a| -
|  > 0  a|       x x1xx xxxx a| Reserved      a| -
|  > 0  a|       x 1xxx xxxx a| Reserved      a| -
|  > 0  a|       1 0000 0000 a| 2 MiB contiguous next-level MPT a| 9
|  > 0  a|       0 xxxx xxxx a| Reserved      a| -
|===

Such MPTEs behave identically to non-leaf MPTEs in the MPT access permission
lookup process described in <<MPT_ACC_LKUP>>, except that:

 * If the encoding in _mpte_ is valid according to <<Smmpt-napot>>,
   then instead of returning the original value of the _mpte_, implicit read
   of a non-leaf NAPOT _mpte_ returns a copy of `mpte` in which
   _mpte.ppn[mpte.napot_bits-1:0]_ are replaced by
   _pa.pn[i][mpte.napot_bits-1:0]_. If the encoding in _mpte_ is reserved
   according to <<Smmpt-napot>> then an access-fault exception corresponding to
   the original access type must be raised.
 * Implicit reads of non-leaf NAPOT MPTEs may create MPT walk cache entries
   mapping _a_ + _j_*PTESIZE to a copy of _mpte_ in which
   _mpte.ppn[mpte.napot_bits-1:0]_ is replaced by _pa.pn[i][mpte.napot_bits-1:0]_,
   for any and all _j_ such that _j_ >> _napot_bits_ = _pa.pn[i]_ >> _napot_bits_.

[NOTE]
====
Some implementations may cache non-leaf MPTEs to accelerate the MPT access-type
permission lookup process using MPT walk caches. Such implementations may then
use the MPTE that was implicitly accessed as one or more entries representing
a contingous set of non-leaf MPTEs at that level. This compaction helps relieve
MPT walk cache pressure in some scenarios. Simpler implementations may simply
create a single entry in their page walk cache using the transformed mpte value
returned by the implicit access to the mpte.

Depending on the need, the NAPOT scheme may be extended to other levels of the
MPT in the future.
====

