
[[Smsdedbga]]

== Supervisor Domain External Trace and Debug Allow Controls

This chapter describes two extensions `Smsdedbga` and `Smsdetrca` that enable
the RDSM to enforce isolation of supervisor domains when external debug and
external trace mechanisms are being utilized.

`Smsdedbga` defines the `SEDA` bit in the `msdcfg` CSR that specifies if a
supervisor domain is allowed to be externally-debugged.

Similarly, `Smsdetrca` defines the `SETA` bit in the `msdcfg` CSR that specifies
if a supervisor domain is allowed to be externally-traced cite:[ExtDbg].

External trace refers to tracing the execution of software running on a separate
target RISC-V platform through a trace control and data transport mechanism that
provides external access to the trace encoder controls cite:[ETrc].

These two extensions only affect debug and trace orchestrated by an external
agent - self-hosted debug (and trace) are managed directly by the RDSM.

This chapter refers to the Debug specification cite:[ExtDbg], Trace specification
cite:[ETrc], and the External debug security extension cite:[ExtDbgSec] for the
description and behavior of controls outside the scope of this specification,
but which interact with controls specified in this specification when one or
more supervisor domains are used.

[NOTE]
====
The values of `msdcfg.SEDA` and `msdcfg.SETA` shall be obtained from the
configuration information defined for the supervisor domain and reflected in the
attestation report for that domain and its workloads. The RDSM shall preserve
and restore this configuration state across context switches using secure
memory.

These configurations allow external debug and trace but do not enable them. If
external debug and/or trace is allowed for a supervisor doamin, an external
debugger may enable the external debug and/or trace for that supervisor domain.
====

=== `Smsdedbga`: External Debug allowed control for Supervisor Domain

When M-mode external debug is enabled, all supervisor domains may also be
debugged by an external debugger irrespective of the configuration held in
`msdcfg.SEDA`.

[NOTE]
====
Whether external debug of M-mode is permitted is determined by the hardware root
of trust (RoT) (cite:[TCGGL]) of the RDSM and is outside the scope of this
specification. When such debug is enabled, the RDSM itself is under debug, and
all supervisor domains managed by the RDSM are implicitly under debug as well.
====

When M-mode external debug is disabled, whether execution at privilege modes
less than `M` may be debugged by an external debugger depends on the
configuration held in `msdcfg.SEDA`, as described below:

If `msdcfg.SEDA` is 0, the hart shall disallow all external debug access using
mechanisms defined in the RISC-V Debug Specification cite:[ExtDbg].

If `msdcfg.SEDA` is 1, the hart shall permit external debug access to privilege
modes less than M.

To enforce the above controls specified by this extension, the following
functional and security requirements cite:[ExtDbgSec] must be met:

* External debug of M-mode can be enabled only by the HW RoT of the RDSM.
* The RDSM must be able to context switch all triggers even when `d-mode` = 1.
  This functional change allows the RDSM to remain in control of external debug
  for supervisor domains when it is not under external debug itself.

=== `Smsdetrca`: External Trace allowed control for Supervisor Domain

When M-mode external trace is enabled, all supervisor domains activity may also
be traced by an external trace tool irrespective of the configuration held in
`msdcfg.SETA`.

[NOTE]
====
Whether external tracing of M-mode is permitted is determined by the hardware
root of trust (RoT) (cite:[TCGGL]) of the RDSM and is outside the scope of this
specification. When such tracing is enabled, the RDSM itself is under debug, and
all supervisor domains managed by the RDSM are implicitly under debug as well.
====

When M-mode external trace is disabled, whether execution at privilege modes
less than M-mode may be traced by an external trace tool depends on the
configuration held in `msdcfg.SETA`, as described below:

If `msdcfg.SETA` is 0, the hart shall disallow all external trace.

If `msdcfg.SETA` is 1, the hart shall permit external trace of privilege
modes less than M, subject to the following requirements:

* When M-mode external tracing is disabled, external tracing shall be
  stopped upon:
** Entry into Debug Mode.
** Entry into M-mode.

To enforce these controls, the following functional and security
requirements cite:[ExtDbgSec] shall be met:

* External trace of M-mode shall be enabled only by the hardware root of
  trust (HW RoT) of the RDSM.
