[[Smsdia]]

== Supervisor Domain Interrupt Assignment

Interrupts that occur during the execution of a supervisor domain cause a trap
to the RDSM in M-mode by default.

To increase performance, the RDSM can delegate the handling of certain
interrupts, like the timer interrupt or the local performance counter
overflow interrupt (LCOFI), to the supervisor domain by setting the
appropriate `mideleg` bits. This delegation could necessitate the RDSM to
context switch additional state related to such delegated interrupts,
including `stimecmp` and the HPM CSRs.

Additionally, the RDSM may assert a _virtual interrupt_ to a supervisor domain.
Such _virtual interrupts_ might be asserted as part of handling a real
interrupt, such as a RAS interrupt, or they may have no direct connection to
any actual interrupt event.

Some supervisor domains may have devices assigned to them for I/O operations.
Devices designed to carry out I/O operations typically signal the completion
of an I/O task or an associated error via an external interrupt. These external
interrupts might be aggregated and indicated by an interrupt controller linked
to the RDSM. The RDSM, in the course of handling an external interrupt, should
forward the interrupt to the relevant supervisor domain. The efficiency of
handling external interrupts by a supervisor domain can be enhanced if the
external interrupts could be directly assigned to the supervisor domain.

To accommodate such supervisor domains, this specification extends the IMSIC
and APLIC specified by the RISC-V Advanced Interrupt Architecture (AIA)
specification cite:[AIA] to support multiple _supervisor interrupt domains_,
enabling an individual _supervisor interrupt domain_ to be associated with each
such supervisor domain.

In some systems, a _supervisor interrupt domain_ in both an APLIC and an IMSIC
may be associated with a supervisor domain, with the supervisor interrupt domain
of the APLIC configured to route interrupts as MSIs to the corresponding
_supervisor interrupt domain_ of the IMSIC.

Interrupt controllers other than APLIC and/or IMSIC that support multiple
_supervisor interrupt domains_ may also serve a supervisor domain.

If there are N implemented _supervisor interrupt domains_, they are numbered
from 0 to N − 1, and the maximum implemented _supervisor interrupt domain
number_ is N − 1.

[[SD-IMSIC]]
=== IMSIC Extension for Supervisor Domains

The IMSIC is extended to support multiple _supervisor interrupt domains_, where
each _supervisor interrupt domain_ may be associated with a supervisor domain.
A _supervisor interrupt domain_ in an IMSIC consists of:

* A supervisor-level interrupt file.
* Optionally, one or more guest interrupt files.

Each _supervisor interrupt domain_ in an IMSIC is identified by a *supervisor
interrupt domain number* (`SIDN`).

When all harts are within a single _hart group_ as defined by cite:[AIA],
the memory-mapped address of the supervisor-level interrupt file for SIDN `n`
and hart `h`, is:

[latexmath]
++++
\text{Address} = B + n \times 2^I + h \times 2^D
++++

Constants `B`, `C`, and `D` in this and later formulas are specified by
cite:[AIA], while `I` is a new constant for supervisor interrupt domains.
Constant `I` must be >= `k + D`, where `k` is the number of bits needed
to represent any hart number `h`.

If the largest _supervisor interrupt domain_ number is stem:[n_{\text{max}}],
then `q` -- the number of bits needed to represent any _supervisor interrupt
domain_ number -- is defined as:

[latexmath]
++++
q = \lceil \log_2(n_{\text{max}} + 1) \rceil
++++

Address `B` must be aligned to a stem:[2^{q + I}] address boundary. (This
automatically makes `B` also aligned to a stem:[2^{k + D}] address boundary
as required by the existing cite:[AIA].)

When there are hart groups, the memory-mapped address of the supervisor-level
interrupt file for group `g`, SIDN `n`, and hart `h` within the group, is:

[latexmath]
++++
\text{Address} = g \times 2^E + B + n \times 2^I + h \times 2^D
++++

Constant `E` must be >= `max(k + C, q + I)`, but will usually be much larger.

The `Smsdia` extension (<<SDI>>) provides the mechanism to select a
_supervisor interrupt domain_ in an IMSIC as a source of supervisor-level and
guest external interrupts for a hart. The interrupt signal from the selected
_supervisor interrupt domain's_ supervisor-level interrupt file appears as bit
`SEIP` in `mip` and `sip`. The interrupt signals from any _guest interrupt
files_ of the selected supervisor interrupt domain appear as active bits in
the hypervisor CSR `hgeip`.

The `siselect` and `sireg` CSRs access the registers of the supervisor-level
interrupt file in the selected _supervisor interrupt domain_. If the selected
_supervisor interrupt domain_ implements _guest interrupt files_ then the
`vsiselect` and `vsireg` CSRs access the registers of a _guest interrupt file_,
of that _supervisor interrupt domain_, as determined by `hstatus.VGEIN`.

[[SD-APLIC]]
=== APLIC Extension for Supervisor Domains

The APLIC supports the concept of multiple interrupt domains where each
interrupt domain may be associated with a subset of RISC-V harts at one
privilege level. To support the Supervisor Domain use cases, the APLIC
must support multiple supervisor-level interrupt domains. A supervisor-level
interrupt domain in the APLIC may be then associated with a Supervisor Domain by
configuring it in _direct delivery mode_ or when the hart uses an IMSIC by
configuring it in _MSI delivery mode_.

To support supervisor domains in MSI delivery mode, the `smsiaddrcfgh` register
is extended with two new parameters called `DXS` (Domain Index Shift) and
`DXW` (Domain Index Width) to help determine the addresses to write outgoing
MSIs. The extended `smsiaddrcfgh` has the following format:

[literal]
....
    bits 28:24     DXS (WARL)
    bits 22:20     LHXS (WARL)
    bits 18:16     DXW (WARL)
    bits 11:0      High Base PPN (WARL)
....

Let `CI` be the Child Index from the `sourcecfg[i]` corresponding to an
interrupt source `_i_`. The MSI target address for this interrupt source
is then computed as follows:

[latexmath]
++++
n = \text{CI} \mathbin{\&} \left( 2^{\text{DXW}} - 1 \right)
++++

[latexmath]
++++
\text{MSI address} =
\left(
  \text{Base PPN}
  \mid ( g \ll (\text{HHXS} + 12) )
  \mid ( n \ll \text{DXS} )
  \mid ( h \ll \text{LHXS} )
  \mid \text{Guest Index}
\right) \ll 12
++++

The parameter `DXS` relates to the constant `I` specified in section <<SD-IMSIC>>
as: `DXS = (I - 12)`.

Refer to cite:[AIA] for the detailed definitions of constants `HHXS`, `g`, `h`,
`LHXS`, and Guest Index.

[[SDI]]
=== "Smsdia" : Standard Extension for Supervisor Domain Interrupt Assignment

The `Smsdia` extension adds supports to select a _supervisor interrupt domain_
in an interrupt controller as a source of supervisor-level and guest external
interrupts for a hart using the `msdcfg` CSR.

The RDSM needs a method to be alerted if an external interrupt, whether a
supervisor-level external interrupt or guest external interrupt, is pending for
any supervisor domains not currently active on a hart. The RDSM could leverage
this notification to inform its scheduling decisions. To facilitate this
functionality, the `Smsdia` extension introduces the `msideip` and `msideie`
CSRs, along with a machine supervisor domain external interrupt (`MSDEI`).

==== Supervisor Interrupt Domain Number

The `Smsdia` extension introduces the _supervisor interrupt domain number_
(`SIDN`) field <<MSDCFG>> of the `msdcfg` register.

The `SIDN` field selects an supervisor interrupt domain among the plurality of
_supervisor interrupt domains_ associated with a hart as the active supervisor
interrupt domain for supervisor-level external interrupt and guest external
interrupts.

The `SIDN` field is a WLRL field that must be able to hold a value between 0
and the maximum implemented _supervisor interrupt domain number_, inclusive.
If there is only a single _supervisor interrupt domain_ connected to the hart,
then `SIDN` may be read-only zero.

When `SIDN` is not the number of an implemented _supervisor interrupt domain_
then the following rules apply:

* The supervisor-level external interrupt pending signal indicated in `mip.SEIP`
  is 0.
* All non-custom values of `siselect` that access IMSIC registers designate an
  _inaccessible_ register. When `siselect` holds the number of an _inaccessible_
  register, attempts from M-mode or HS-mode to access `sireg` raise an illegal
  instruction exception.
* Access to CSR `stopei` raises an illegal instruction exception.
* The `hstatus.vgein` field is read-only zero.
* `hgeip` and `hgeie` are read-only 0.

When the _supervisor interrupt domain_ selected by `msdcfg.SIDN` is an
implemented, and is an IMSIC, the following rules apply:

* The supervisor-level external interrupt pending signal of supervisor-level
  interrupt file of the selected _supervisor interrupt domain_ is indicated in
  `mip.SEIP`.
* The `siselect` and `stopei` CSRs operate on the registers of the
  supervisor-level interrupt file in the selected _supervisor interrupt
  domain_.
* The guest external interrupt pending signals of the _guest interrupt files_
  of selected _supervisor interrupt domain_ are indicated in the `hgeip` CSR.
* The `hstatus.VGEIN` selects a _guest interrupt file_ in the selected supervisor
  interrupt domain and `vsiselect` and `vstopei` CSRs operate on the registers
  of the corresponding _guest interrupt file_.

When the _supervisor interrupt domain_ selected by `msdcfg.SIDN` is implemented,
and is an APLIC, the following rules apply:

* The supervisor-level external interrupt pending signal of the selected APLIC
  _supervisor interrupt domain_ is indicated in `mip.SEIP`.

[NOTE]
====
The `Smsdia` extension provides for directly associating a _supervisor interrupt
domain_ with up to 64 supervisor domains. The RDSM may emulate interrupt
controllers for additional supervisor domains.

To emulate an IMSIC _supervisor interrupt domain_, the RDSM may use the illegal
instruction trap facilitated by AIA-added state-enable bits to
`mstateen0/mstateen0h` for emulation purposes.
====

==== Hypervisor Guest External Interrupt Registers (`hgeip` and `hgeie`)

When the H extension is also implemented, the implementation must internally
maintain an array of registers that hold the state of the `hgeip` and `hgeie`
CSRs, with one pair of registers per implemented supervisor interrupt domain
number. The `hgeip` and `hgeie` CSRs access the element of this array
corresponding to the value of `msdcfg.SIDN`.

==== Machine supervisor interrupt domain external interrupt pending (`msideip/msideiph`)

The `msideip` is a 64-bit read-only register, formatted as shown in <<MSIDEIP>>.
The CSR number is 0xF4F.

When MXLEN=32, `msideiph` is a 32-bit read-only register which aliases bits
63:32 of `msideip`. The CSR number is 0xF5F. When MXLEN=64, `msideiph` does not
exist.

[[MSIDEIP]]
.`msideip` register

[wavedrom, , ]
....
{reg: [
  {bits: 64, name: 'Interrupts'},
], config:{lanes: 1, hspace:1024}}
....

Each bit __i__ in the register summarizes the external interrupts pending in the
_supervisor interrupt domain_ numbered __i__.

When the _supervisor interrupt domain_ identified by __i__ is implemented by an
APLIC, the bit __i__ indicates the state of the supervisor-level external interrupt
pending signal provided by the _supervisor interrupt domain_ in that APLIC.

When the _supervisor interrupt domain_ identified by __i__ is implemented by an
IMSIC, bit __i__ must be set to one if and only if either of the following
conditions holds:

* the SEIP signal for _supervisor interrupt domain_ __i__ is asserted; or
* the bitwise logical AND of the internal `hgeip` and `hgeie` registers for
  _supervisor interrupt domain_ __i__ is nonzero (i.e., the value that SGEIP
  would have for that domain).

The summary of external interrupts pending in a _supervisor interrupt domain_ is
visible in the `msideip` register even when `msdcfg.SIDN` is not the valid number
of an implemented _supervisor interrupt domain_.

==== Machine supervisor interrupt domain external interrupt enable (`msideie/msideieh`)

The `msideie` is a 64-bit read-write register, formatted as shown in <<MSIDEIE>>.
The CSR number is 0x74F.

When MXLEN=32, `msideieh` is a 32-bit read-write register which aliases bits
63:32 of `msideie`. The CSR number is 0x75F. When MXLEN=64, `msideieh` does not
exist.

[[MSIDEIE]]
.`msideie` register

[wavedrom, , ]
....
{reg: [
  {bits: 64, name: 'Interrupts (WARL)'},
], config:{lanes: 1, hspace:1024}}
....

The `msideie` CSR selects the subset of _supervisor interrupt domains_ that
cause a machine supervisor domain external interrupt (`MSDEI`). The enable
bits in `msideie` do not affect the supervisor-level external interrupt and
guest external interrupt pending signals from the _supervisor interrupt
domain_ selected by `msdcfg.SIDN`.

==== Machine and Supervisor Interrupt registers (`mip/mie` and `sip/sie`)

The `Smsdia` extension introduces the machine supervisor domain external
interrupt (`MSDEI`). This interrupt is assigned to bit 14 in the `mip`,
`mie`, `sip`, and `sie` registers. The bit 14 in `mip` and `sip` is called
`MSDEIP` and the same bit in `mie` and `sie` is called `MSDEIE`. The
`mideleg` register controls the delegation of `MSDEI` to S-mode. This
interrupt cannot be delegated to VS-mode and bit 14 of `hideleg` is
read-only zero.

The `mip.MSDEIP` bit read-only and is set to 1 if the bitwise logical AND of CSRs
`msideip` and `msideie` is nonzero in any bit. The `mie.MSDEIE` bit is writable.

When bit 14 of `mideleg` is zero, `sip.MSDEIP` and `sie.MSDEIE` are read-only
zeros. Else, `sip.MSDEIP` and `sie.MSDEIE` are aliases of `mip.MSDEIP` and
`mie.MSDEIE`.

Multiple simultaneous interrupts destined for different privilege modes are
handled in decreasing order of destined privilege mode. For the base Privileged
ISA's major interrupts (numbers 0-15), multiple simultaneous interrupts destined
for the same privilege mode are handled in the following decreasing default
priority order: MEI, MSI, MTI, MSDEI, SEI, SSI, STI, SGEI, VSEI, VSSI, VSTI,
LCOFI.

[NOTE]
====
The RDSM may use the machine supervisor interrupt domain external interrupt to determine if
a supervisor domain has become ready to run since it was last descheduled. When
a supervisor domain that has a supervisor domain interrupt controller directly
assigned to it, the RDSM updates the `msdcfg.SIDN` to select that supervisor
interrupt domain and may clear the bit corresponding to that supervisor
interrupt domain in `msideie` prior to resuming execution of the supervisor
domain.

The RDSM may delegate `MSDEI` to a supervisor domain that may be entrusted by
the RDSM to get notified about supervisor domain external interrupts pending for
one or more other supervisor domains. Typically, this use case involves a single
supervisor domain that is trusted by the RDSM to receive such notifications. The
delegation supports optimizing the exit sequence from such supervisor domain by
enabling such supervisor domains to voluntarily yield execution in response to
pending interrupts for the other supervisor domains.
====

=== "Smgeien/Ssgeien" : Standard Extension for Machine Guest External Interrupt Enables

The `Smgeien` extension enables access to a subset of the guest interrupt
files within a _supervisor interrupt domain_ in an IMSIC to a supervisor domain.
The `Smgeien` extension depends on the `Smsdia` extension.

The `Smgeien` extension depends on the `Smaia` and the H extension.
When `Smgeien` is implemented, the bit 9 of `mvien` must be writable.

This extension introduces an MXLEN read-write WARL register named `mgeien`,
formatted as shown in <<MGEIEN>> for RV64 and in <<MGEIEN32>> for RV32. The CSR
number is 0x74D.

[[MGEIEN]]
.`mgeien` register for RV64

[wavedrom, , ]
....
{reg: [
  {bits:  1, name: 'A'},
  {bits: 63, name: 'GIF'},
], config:{lanes: 1, hspace:1024}}
....

[[MGEIEN32]]
.`mgeien` register for RV32

[wavedrom, , ]
....
{reg: [
  {bits:  1, name: 'A'},
  {bits: 31, name: 'GIF'},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
====
The RDSM may use bit 9 of `mvien` to control access to the supervisor-level
interrupt file in the _supervisor interrupt domain_ selected by `msdcfg.SIDN`.
====

Each bit of the `GIF` field when set to 1 enables access to corresponding _guest
interrupt file_ in the _supervisor interrupt domain_ selected by `msdcfg.SIDN`.

The number of writable bits in mgeien is determined by the maximum `GEILEN`
value across all supervisor interrupt domains, and this maximum is referred to
as `MGEILEN`. If `MGEILEN` is nonzero, bits `MGEILEN:1` shall be writable in
`mgeien`. All other bit positions in the `GIF` field shall be read-only zeros.

For a supervisor-level environment, extension `Ssgeien` is essentially the same
as `Smgeien` except excluding the machine-level CSRs and behavior not directly
visible to supervisor level.

If the _supervisor interrupt domain_ selected by `msdcfg.SIDN` is implemented
then:

* Bits `GEILEN:1` of `hgeip` are read-only aliases of the same bits in the
  internal `hgeip` register selected by `msdcfg.SIDN` if the bit at the same
  position in `mgeien` is 1. All other bits of `hgeip` are zero.

* Bits `GEILEN:1` of `hgeie` are writable aliases of the same bits in the
  internal `hgeie` register selected by `msdcfg.SIDN` if the bit at the same
  position in `mgeien` is 1. All other bits of `hgeie` are read-only zero.

* If `hstatus.VGEIN` is not 0 and the bit selected by `VGEIN` in `mgeien` is 1
  then the `vsiselect`, `vsireg`, and `vstopei` CSRs operate on the registers of
  the _guest interrupt file_ selected by `VGEIN`. If `VGEIN` is 0 or the the bit
  selected by `VGEIN` in `mgeien` is 0 then the `vsiselect`, `vsireg`, and
  `vstopei` CSRs operate as-if the `VGEIN` is the number of an unimplemented
  guest external interrupt.

The `mgeien.A` bit, when set to 1, enables `msideip` to accumulate all external
interrupts for the supervisor interrupt domain; otherwise, `msideip` accumulates
only the subset of guest external interrupts determined by `mgeien.GIF`. When
`mgeien.A` is 0, the SEIP for the supervisor interrupt domain is accumulated in
`msideip` if it is not delegated to the supervisor domain.

Each bit __i__ of `msideip`, corresponding to an implemented _supervisor
interrupt domain_, must be set to one if and only if the relevant interrupt
source is active.

Specifically:

* If __i__ equals `msdcfg.SIDN`, the bit is set to one if and only if either:

** `mip.SEIP` is 1 and bit 9 (for SEI) of `mideleg` is zero; or

** `mip.SEIP` is 1 and `mgeien.A` is 1; or

** The bitwise logical AND of the following three components of the _supervisor
   interrupt domain_ is nonzero:
   *** the _internal_ `hgeip`,
   *** the _internal_ `hgeie`, and
   *** the _logical complement_ of `mgeien` if `mgeien.A` is 0; otherwise, a
       value of all 1s.

[NOTE]
====
The `Smgeien` extension is intended for use cases involving supervisor domains
that share the guest interrupt files in a _supervisor interrupt domain_.

Typically, one of the supervisor domains participating in the scheme acts as
a donor domain that initially has access to all the interrupt files. Such a
donor supervisor domain may then donate one or more interrupt files--usually
_guest interrupt files--to a recipient supervisor domain, either temporarily
or permanently, by invoking SBI functions provided by the RDSM. Once the
interrupt files have been made accessible to the recipient domain by the RDSM,
the donor domain is not expected to access them.

Recipient domains must not assume that the donated interrupt files are
contiguously laid out in memory, nor should they expect the corresponding bits
in `hgeip` and `hgeie` to be contiguous. Furthermore, a recipient must not
assume it can use a supervisor-level interrupt file unless it has been
explicitly made accessible. This behavior is indicated by the `Ssgeien`
extension.

The memory locations of the accessible guest interrupt files, along with their
guest external interrupt numbers, are communicated to recipient supervisor
domains by the RDSM through software mechanisms such as SBI.
====
