[[chapter3]]

== Supervisor Domain Identifier and Protection Register (mttp) 

The `mttp` register is an XLEN-bit read/write register, formatted as shown in Figure 3.1 for XLEN=32 and Figure 3.2 for XLEN=64, which controls physical address protection for supervisor domains (see Section 2). This register holds the physical page number (PPN) of the root page of the memory tracking table (MTT). The MTT is a structure that holds the read, write access permission bits for a physical address; a supervisor domain identifier (SDID), which facilitates address protection fences on a per-supervisor-domain basis; and the MODE field, which selects the address protection scheme for physical addresses. 

Attempts to read or write mttp while executing in U, S or HS-mode will raise an illegal instruction exception. 

[width="100%",cols="9%,6%,11%,11%,20%,43%",options="header",]
[frame=none, grid=none]
|===
<|31 
>|30
<|29 
>|22
<|21 
>|0
|===
[width="100%",cols="9%,6%,11%,11%,20%,43%",options="header",]
|===
2+^| Mode (WARL) 
2+^| SDID (WARL) 
2+^| MTPPN (WARL)
|===
[width="100%",cols="9%,6%,11%,11%,20%,43%",options="header",]
[frame=none, grid=none]
|===
2+^|2 
2+^|8 
2+^|22
|===

Figure 3.1: mttp when XLEN=32 for MODE values Bare, Smmtt34.

[width="100%",cols="11%,6%,16%,4%,20%,43%",options="header",]
[frame=none, grid=none]
|===
<|63 
>|60 
<|59 
>|44 
<|43 
>|0
|===

[width="100%",cols="11%,6%,16%,4%,20%,43%",options="header",]
|===
2+^|Mode (WARL) 
2+^|SDID (WARL) 
2+^|MTPPN (WARL)
|===

[width="100%",cols="11%,6%,16%,4%,20%,43%",options="header",]
[frame=none, grid=none]
|===
2+^|4 
2+^|16 
2+^|44
|===

Figure 3.2: mttp when XLEN=64, for MODE values Bare, Smmtt46, Smmtt56.

Table 3.1 shows the encodings of the MODE field when XLEN=32 and XLEN=64. When mttp MODE=Bare, supervisor physical addresses have no MTT-based protection across supervisor domains beyond the physical memory protection scheme described in Section 3.7 of the RISC-V privileged architecture specification [1]. In this case, the remaining fields (SDID, MTTPPN) in mttp must be set to zeros, else generate a fault. When XLEN=32, the other valid settings for MODE are Smmtt34 and Smmtt34rw, to support allow/disallow and read-write access permissions for 34-bit system physical addresses. 

When XLEN=64, other than BARE, the other valid settings for MODE are Smmtt[46, 56][rw] to support read-write/access permissions for 56-bit system physical addresses. 

The remaining MODE settings when XLEN=64 are reserved for future use and may define different interpretations of the other fields in mttp. 

[width="100%",cols="10%,14%,76%",options="header",]
|===
|Value |Name |Description
|0 |Bare |No inter-supervisor domain protection

|1 |Smmtt34 |Page-based supervisor domain protection for 34 bit physical
addresses with access allowed/disallowed per page

|2 |Smmtt34rw |Page-based supervisor domain protection for 34 bit
physical addresses with RW permissions per page
|===

Table 3.1: Encoding of mttp MODE field for XLEN=32.

[width="100%",cols="10%,14%,76%",options="header",]
|===
|Value |Name |Description
|0 |Bare |No inter-supervisor domain protection

|1 |Smmtt46 |Page-based supervisor domain protection for 46 bit physical
addresses

|2 |Smmtt46rw |Page-based supervisor domain protection for 46 bit
physical addresses with RW permissions per page

|3 |Smmtt56 |Page-based supervisor domain protection for 56 bit physical
addresses

|4 |Smmtt56rw |Page-based supervisor domain protection for 46 bit
physical addresses with RW permissions per page

|3-15 |- |_Reserved_
|===

Table 3.2: Encoding of mttp MODE field for XLEN=64.

Implementations are not required to support all defined MODE settings when XLEN=64. A write to mttp with an unsupported MODE value is not ignored. Instead, the fields of mttp are WARL in the normal way, when so indicated. 

The MTTPPN refers to an MTT L3 table or an MTT L2 table based on physical address width (PAW). For 56<=PAW<46, L3 table must be of size 2^(PAW-43) bytes and naturally aligned to that sized byte boundary. For 46<=PAW<32 the MTT L2 table must be of size 2^(PAW-23) or 2^(PAW-22) bytes (depending on the Smmtt mode selected) and must be naturally aligned to that sized byte boundary. In these modes, the lowest two bits of the physical page number (PPN) in mttp always read as zeros. 

The number of SDID bits is UNSPECIFIED and may be zero. The number of implemented SDID bits, termed SDIDLEN, may be determined by writing one to every bit position in the SDID field, then reading back the value in mttp to see which bit positions in the SDID field hold a one. The least-significant bits of SDID are implemented first: that is, if SDIDLEN > 0, SDID[SDIDLEN-1:0] is writable. The maximal value of SDIDLEN, termed SDIDMAX, is 8 for Smmtt34[rw] or 16 for Smmtt46[rw], Smmtt56[rw]. 

The mttp register is considered active for the purposes of the physical address protection algorithm unless the effective privilege mode is M. 

Physical accesses that began while mttp was active are not required to complete or terminate when mttp is no longer active, unless an FENCE.MTT instruction matches the SDID (and address?) is executed. The FENCE.MTT instruction must be used to ensure that updates to the MTT address protection data structures are observed by subsequent implicit reads to those structures by a hart.

Note that writing mttp does not imply any ordering constraints between S-mode and G-stage page-table updates and subsequent address translations. If a supervisor domain's physical page protection structure has been modified, or if a SDID is reused, it may be necessary to execute an FENCE.MTT instruction before or after writing mttp.



