[[chapter4]]
[[Smmpt]]
== Machine-mode Memory Protection Table (MPT)

Memory Protection table is a radix-tree table used to provide read, write, and
execute permissions for implicit and explicit memory accesses by effective
privilege modes less than M.

The following MPT extensions are defined:

* Smmpt34 - Page-based 34-bit memory protection system (RV32 only)
* Smmpt43 - Page-based 43-bit memory protection system (RV64 only)
* Smmpt52 - Page-based 52-bit memory protection system (RV64 only)
* Smmpt64 - Page-based 64-bit memory protection system (RV64 only)

These MPT extensions depend on `Smsdid`.

=== Smmpt34: Page-Based Memory Protection System

The RV32 Memory Protection Table provides memory access type permissions
for pages in a 34-bit supervisor physical address (SPA) space. The SPA is
partitioned into a page number (`pn`) and a range offset. When the Smmpt34 mode
is selected in the `MODE` field of `mmpt`, the access type permissions for a
supervisor physical address are determined using a two-level memory protection
table.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="RV32 Supervisor Physical Address", id=rv32-spa]
[wavedrom, ,svg]
....
{reg: [
  {bits:  15, name: 'range offset', attr: '15'},
  {bits:  10, name: 'pn[0]',        attr: '10' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The root memory protection table has 2^9^ memory-protection-table entries
(MPTEs) and the memory protection tables linked to the root table have 2^10^
MPTEs. Each MPTE is a four byte value. Each memory protection table,
including the root MPT, must always be aligned to a page boundary.

If the MPTE points to the next level of the memory protection table, it is a
non-leaf MPTE, else it is a leaf MPTE. A leaf MPTE provides access type
permissions for eight pages in the address range determined by that MPTE.

The format of a non-leaf MPTE entry is shown in <<rv32-mpte>> and that of a leaf
MPTE entry in <<rv32-mpte-leaf>>.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="`Smmpt34` non-leaf `MPTE`", id="rv32-mpte"]
[wavedrom, ,svg]
....
{reg: [
  {bits:  1,  name: 'V=1'},
  {bits:  1,  name: 'L=0'},
  {bits:  8,  name: 'Reserved'},
  {bits:  22, name: 'PPN'},
], config:{lanes: 1, hspace:1024}}
....

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="`Smmpt34` non-NAPOT leaf `MPTE`", id="rv32-mpte-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:  1,  name: 'V=1'},
  {bits:  1,  name: 'L=1'},
  {bits:  1,  name: 'N=0'},
  {bits:  5,  name: 'Reserved'},
  {bits:  3,  name: 'XWR[0]'},
  {bits:  3,  name: 'XWR[1]'},
  {bits:  3,  name: 'XWR[2]'},
  {bits:  3,  name: 'XWR[3]'},
  {bits:  3,  name: 'XWR[4]'},
  {bits:  3,  name: 'XWR[5]'},
  {bits:  3,  name: 'XWR[6]'},
  {bits:  3,  name: 'XWR[7]'},
], config:{lanes: 4, hspace:1024}}
....

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="`Smmpt34` NAPOT leaf `MPTE`", id="rv32-mpte-napot-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:  1,  name: 'V=1'},
  {bits:  1,  name: 'L=1'},
  {bits:  1,  name: 'N=1'},
  {bits:  5,  name: 'Reserved'},
  {bits:  3,  name: 'XWR'},
  {bits:  1,  name: 'Reserved'},
  {bits:  4,  name: 'G'},
  {bits: 16,  name: 'Reserved'},
], config:{lanes: 4, hspace:1024}}
....

The `V` bit indicates if the MPTE is valid; if it is 0, all other bits in the
MPTE are don't-cares and may be used freely by software. When the `MPTE` is
valid, the bits constituting the `RESERVED` field are reserved for future
standard use and, until its use is defined by some standard extension,
must be zeroed by software for forward compatibility. If any of these
bits are set, an access-fault exception is raised.

Explicit stores by a hart that update the `V` bit of leaf and/or non-leaf MPTEs
from 0 to 1 and are visible to a hart will eventually become visible within a
bounded timeframe to subsequent implicit accesses by that hart to such MPTEs.

[NOTE]
====
This behavior relieves M-mode software from executing certain memory-management
instructions, such as MFENCE.MPA or MINVAL.MPA, which would normally be used to
synchronize the hart’s MPT caches when a memory-resident MPTE is changed from
Invalid to Valid. Synchronizing the hart’s MPT caches with other forms of updates
to a memory-resident MPTE, including when a MPTE is changed from Valid to Invalid,
requires the use of suitable memory-management instructions. This behavior
guarantees that a change to a MPTE from Invalid to Valid is made visible within a
bounded time, thereby making the execution of these memory-management
instructions redundant. The performance benefit of eliding these instructions
outweighs the cost of an occasional gratuitous additional access fault that may occur.

Depending on the microarchitecture, some possible ways to facilitate include:
not storing Invalid PTEs in the MPT page-walk caches, automatically evicting
Invalid MPTEs using a bounded timer, or making MPT page-walk caches coherent
with store instructions that modify MPTEs.
====

When the `L` bit is set to 0, the entry is a non-leaf MPTE, else it is a leaf MPTE.

When `MPTE.L`=1 and `MPTE.N`=1, the leaf `MPTE` represents a memory protection
range that is part of a larger contiguous NAPOT memory protection range comprised
of `2^(G+1)` MPTEs. All leaf MPTEs at that level of this NAPOT memory protection
range have the same value for L, N, XWR and V bits. The encodings 0-5 and 7-15
of `G` are reserved for Smmpt34. The format of a NAPOT leaf MPTE is shown in
<<rv32-mpte-napot-leaf>>.

[NOTE]
====
The motivation of NAPOT MPTE is that access-type permissions for one or more
entries representing the contiguous region may be cached as a single cache entry
as if it were a single (large) page. This compaction can relieve access-type
permission caches. The scheme allows an implementation to not take advantage of
this property and simply cache the access-type permissions for pages separately.

The encoding of G=6 supports caching a single access-type permission entry
representing a 4 MiB address range. Depending on need, the NAPOT scheme may be
extended to other page sizes in the future. The encoding is designed to
accommodate other NAPOT sizes should that need arise.
====

A non-leaf MPTE holds the PPN of the next level of the memory protection table.

A leaf MPTE holds eight tuples of access type permission bits - one for each
page in the range determined by that MPTE. Each tuple consists of 3 bits `XWR`,
that provide the Execute (`X`), Write (`W`), and Read (`R`) permissions. The most
significant 3 bits of the range offset identify a page in that range and are
used to identify the access type permission bits for an access to that page.

[[Smmpt-xwr-encoding]]
.Encoding of `MPTE` X/W/R permission tuple
[%autowidth,float="center",align="center",cols="^,^,^,<",options="header"]
|===
| X | W | R | Meaning
| 0 | 0 | 0 | No access.
| 0 | 0 | 1 | Read-only page.
| 0 | 1 | 0 | _Reserved for future use._
| 0 | 1 | 1 | Read-write page.
| 1 | 0 | 0 | Execute-only page.
| 1 | 0 | 1 | Read-execute page.
| 1 | 1 | 0 | _Reserved for future use._
| 1 | 1 | 1 | Read-write-execute page.
|===

Access type permissions -- readable, writable, or executable -- are checked
by MPT the same as for VS-stage and G-stage translation. For a memory access
made to support VS-stage or G-stage address translation (such as a read/write to
a VS-stage page table or a G-stage page table), permissions are checked as
though for an implicit load or store, not for the original access type. However,
any exception is always reported for the original access type (instruction,
load, or store/AMO).

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt34 supports 4 MiB pages.

[[MPT_ACC_LKUP]]
==== MPT access type permissions lookup process
Access type permissions for a physical address PA are determined as
follows:

1. Let _a_ be `mmpt.ppn` x PAGESIZE, and let _i_ = LEVELS-1 (For Smmpt34,
   PAGESIZE is 2^12^ and LEVELS=2). The `mmpt` register must be active,
   i.e., the effective privilege mode must not be M-mode.

2. Let _mpte_ be the value of the `MPTE` at address _a_ + _pa.pn[i]_
   x MPTESIZE (For Smmpt34, MPTESIZE=4). If accessing _mpte_ violates a PMA
   or PMP check, raise an access-fault exception corresponding to the original
   access type.

3. If _mpte.V_=0, or if any bits or encodings that are reserved for future
   standard use are set within _mpte_, or if _mpte.L_ = 0 and _mpte.N_ = 1,
   stop and raise an access-fault exception corresponding to the original
   access type.

4. Otherwise, the _mpte_ is valid. If _mpte.L=1_ go to step 5; Otherwise, this
   MPTE is a pointer to the next level of the memory protection table. Let
   _i_=_i_-1. If _i_<0, stop and raise an access-fault exception corresponding
   to the original access type. Otherwise, let _a_ = _mpte.PPN_ x PAGESIZE and
   go to step 2.

5. If _mpte.N_=0, a non-NAPOT leaf _mpte_ has been found. If _i_ > 0, let _pi_
   be the value of the NUMPGINRANGE most significant bits of _pa.pn[i-1]_.
   Otherwise, for _i_ = 0, let _pi_ be the value of the NUMPGINRANGE most
   significant bits of the range offset specified in the _pa_.
   (For Smmpt34, NUMPGINRANGE is 3). Let _XWR=mpte.XWR[pi]_.

6. If _mpte.N_=1, a NAPOT leaf _mpte_ has been found. Let _XWR=mpte.XWR_. If
   the value of _G_ is reserved for the current MPT mode, raise an access-fault
   exception corresponding to the original access type.

7. Determine if the requested memory access is allowed by the _XWR_ bits, given
   the effective privilege mode and MXR field of the `mstatus` register. If not,
   stop and raise an access-fault exception corresponding to the original access
   type, else the requested memory access is allowed.

Implicit accesses to MPT by this process are checked by PMP/Smepmp as implicit
M-mode accesses. The endianness of such implicit accesses is controlled by
`mstatus.MBE`.

=== Smmpt43: Page-Based 43-bit Memory Protection System

This section describes a page-based memory protection system for RV64, which
supports a 43-bit supervisor physical address space. The design of Smmpt43
follows the overall scheme of Smmpt34, and this section details only the
differences between the schemes.

[NOTE]
====
Multiple memory protection systems are specified for RV64 to relieve the tension
between providing a large physical address space and minimizing the memory
protection cost. For many systems, 43-bits of physical address space is ample,
and so Smmpt43 suffices. Smmpt52 increases the physical address space to 52
bits, but increases the physical memory capacity dedicated to memory protection
tables and the latency of memory protection table traversals. Smmpt64 increases
the physical address space to 64 bits.
====

Smmpt43 supports a 43-bit supervisor physical address space, divided into pages. The
Smmpt43 address is partitioned as shown in  <<rv64-spa-Smmpt43>>. The supervisor
physical address must have bits 43 and higher all equal to 0, or else an
access-fault exception corresponding to the original access type will occur. The
Smmpt43 memory protection table has three levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt43 Supervisor Physical Address", id=rv64-spa-Smmpt43]
[wavedrom, ,svg]
....
{reg: [
  {bits:  16, name: 'range offset', attr: '16'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt43 memory protection tables contain 2^9^ memory protection table
entries (MPTEs). Each Smmpt43 MPTE is an eight byte value. A page table is
exactly the size of a page and must always be aligned to a page boundary.
The physical page number of the root memory protection table is stored in the
`mmpt` register's PPN field.

The format of a non-leaf MPTE entry is shown in <<rv64-mpte>> and that of a leaf
MPTE entry in <<rv64-mpte-leaf>>. The format of a NAPOT leaf MPTE is shown
in <<rv64-mpte-napot-leaf>>.

A leaf MPTE provides access type permissions for sixteen pages in the address
range determined by that MPTE.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt43 non-leaf `MPTE` entry", id="rv64-mpte"]
[wavedrom, ,svg]
....
{reg: [
  {bits:   1, name: 'V'},
  {bits:   1, name: 'L=0'},
  {bits:   8, name: 'Reserved'},
  {bits:  44, name: 'PPN'},
  {bits:  10, name: 'Reserved'},
], config:{lanes: 2, hspace:1024}}
....

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt43 non-NAPOT leaf `MPTE` entry", id="rv64-mpte-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:   1, name: 'V'},
  {bits:   1, name: 'L=1'},
  {bits:   1, name: 'N=0'},
  {bits:   5, name: 'Reserved'},
  {bits:   3, name: 'XWR[0]'},
  {bits:   3, name: 'XWR[1]'},
  {bits:   3, name: 'XWR[2]'},
  {bits:   3, name: 'XWR[3]'},
  {bits:   3, name: 'XWR[4]'},
  {bits:   3, name: 'XWR[5]'},
  {bits:   3, name: 'XWR[6]'},
  {bits:   3, name: 'XWR[7]'},
  {bits:   3, name: 'XWR[8]'},
  {bits:   3, name: 'XWR[9]'},
  {bits:   3, name: 'XWR[10]'},
  {bits:   3, name: 'XWR[11]'},
  {bits:   3, name: 'XWR[12]'},
  {bits:   3, name: 'XWR[13]'},
  {bits:   3, name: 'XWR[14]'},
  {bits:   3, name: 'XWR[15]'},
  {bits:   8, name: 'Reserved'},
], config:{lanes: 4, hspace:1024}}
....

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt43 NAPOT leaf `MPTE` entry", id="rv64-mpte-napot-leaf"]
[wavedrom, ,svg]
....
{reg: [
  {bits:   1, name: 'V'},
  {bits:   1, name: 'L=1'},
  {bits:   1, name: 'N=1'},
  {bits:   5, name: 'Reserved'},
  {bits:   3, name: 'XWR'},
  {bits:   1, name: '0'},
  {bits:   4, name: 'G'},
  {bits:  48, name: 'Reserved'},
], config:{lanes: 4, hspace:1024}}
....

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt43 supports 2 MiB, and 1 GiB pages.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 3, MPTESIZE equals 8, and NUMPGINRANGE
equals 4.

The encodings 0-3 and 5-15 of `G` are reserved for Smmpt43.

[NOTE]
====
The encoding of G=4 supports caching a single access-type permission entry
representing a 2 MiB or a 1 GiB address range. These contiguous address range
sizes represent large/huge page sizes used commonly by memory allocators.

Depending on need, the NAPOT scheme may be extended to other page sizes in
the future.
====

=== Smmpt52: Page-Based 52-bit Memory Protection System

This section describes a page-based memory protection system for RV64 that
supports 52-bit supervisor physical address spaces. It closely follows the design of
Smmpt43, simply adding an additional level of page table, and so this section
only details the differences between the two schemes.

Smmpt52 supports a 52-bit supervisor physical address space, divided into pages. The
Smmpt52 address is partitioned as shown in  <<rv64-spa-Smmpt52>>. The supervisor
physical address must have bits 52 and higher all equal to 0, or else an
access-fault exception corresponding to the original access type will occur. The
Smmpt52 memory protection table has four levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt52 Supervisor Physical Address", id=rv64-spa-Smmpt52]
[wavedrom, ,svg]
....
{reg: [
  {bits:  16, name: 'range offset', attr: '16'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
  {bits:  9,  name: 'pn[3]',        attr: '9'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt52 memory protection tables contain 2^9^ memory protection table
entries (MPTEs). Each MPTE is an eight byte value. A page table is exactly the
size of a page and must always be aligned to a page boundary. The physical page
number of the root memory protection table is stored in the `mmpt` register's
PPN field.

The MPTE formats for Smmpt52 are identical to that of Smmpt43.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt52 supports 2 MiB, 1 GiB, and 512 GiB pages.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 4, MPTESIZE equals 8, and NUMPGINRANGE
equals 4.

The encodings 0-3 and 5-15 of `G` are reserved for Smmpt52.

=== Smmpt64: Page-Based 64-bit Memory Protection System

This section describes a page-based memory protection system for RV64 that
supports 64-bit supervisor physical address spaces. It closely follows the design of
Smmpt52, simply adding an additional level of page table, and so this section
only details the differences between the two schemes.

Smmpt64 supports a 64-bit supervisor physical address space, divided into pages. The
Smmpt64 address is partitioned as shown in  <<rv64-spa-Smmpt64>>. The
Smmpt64 memory protection table has five levels.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="Smmpt64 Supervisor Physical Address", id=rv64-spa-Smmpt64]
[wavedrom, ,svg]
....
{reg: [
  {bits:  16, name: 'range offset', attr: '16'},
  {bits:  9,  name: 'pn[0]',        attr: '9' },
  {bits:  9,  name: 'pn[1]',        attr: '9'},
  {bits:  9,  name: 'pn[2]',        attr: '9'},
  {bits:  9,  name: 'pn[3]',        attr: '9'},
  {bits:  12, name: 'pn[4]',        attr: '12'},
], config:{lanes: 1, hspace:1024}}
....

The Smmpt64 root memory protection table contain 2^12^ memory protection
table entries (MPTEs). Each MPTE is an eight bytes value. The root memory
protection table is 32 KiB instead of the usual 4 KiB and must be aligned to a
32 KiB boundary. The physical page number of the root memory protection table is
stored in the `mmpt` register's PPN field.

The non-root Smmpt64 memory protection tables contain 2^9^ MPTEs, eight bytes
each. The non-root memory protection table is exactly the size of a page and
must always be aligned to a page boundary.

The MPTE formats for Smmpt64 are identical to that of Smmpt52.

Any level of MPTE may be a leaf MPTE, so in addition to providing access type
permissions to 4 KiB pages, Smmpt64 supports 2 MiB, 1 GiB, 512 GiB, and 256 TiB
pages.

The algorithm to determine access type permissions for a page is same as in
<<MPT_ACC_LKUP>>, except LEVELS equals 5, MPTESIZE equals 8, and NUMPGINRANGE
equals 4.

The encodings 0-3 and 5-15 of `G` are reserved for Smmpt64.
